### PR TITLE
regrunt to fix merge conflicts

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by blankenberg** [comment]
ping @guerler

**Comment by blankenberg** [comment]
Looks like merging https://github.com/galaxyproject/galaxy/pull/781 has just caused additional conflicts. 

Going to close this PR and stop testing.

**Comment by dannon** [comment]
@blankenberg Sorry for the inconvenience, @guerler and I have been pinging back and forth working on this stuff out of band.  I'll pick it up and test/merge.

**Comment by blankenberg** [comment]
@dannon would recommend the use of WIP tags for occasions such as this.

**Comment by dannon** [comment]
@blankenberg Probably would have been a good idea.

**Pull request closed without merging**
